Take platform as an argument
Copied from Perforce
 Change: 18875
 ServerID: perforce.ravenbrook.com

diff --git a/mps/home/bin/build/MM_src_trunk b/mps/home/bin/build/MM_src_trunk
--- a/mps/home/bin/build/MM_src_trunk
+++ b/mps/home/bin/build/MM_src_trunk
@@ -1,14 +1,15 @@
-#!/bin/sh
+#!/usr/local/bin/bash
 #
 # Build and test MM at tip of main trunk (the MM_src compound)
 # 
-# $HopeName: HOMEmm!bin:build:MM_src_trunk(trunk.17) $
+# $HopeName: HOMEmm!bin:build:MM_src_trunk(trunk.18) $
 #
 
 script="`basename $0`"
+platform=$1
 
 msg () {
-  echo "$script: $*" 1>&2
+  echo "$script $platform: $*" 1>&2
 }
 
 die () {
@@ -33,21 +34,24 @@ cd src &&
 
 for lib in mps.a mmsw.a
 do
-  gnumake -r -f sus8gc.gmk $lib ||
+  gnumake -r -f ${platform}.gmk $lib ||
     die "Unable to build library $lib of trunk"
-done &&
+done
 
 for test in amcss lockcov locv mpmss mpsicv poolncv \
             qs mpmconft finalcv arenacv awlut
             ## Don't run amsss, because it doesn't work
             ## Don't run dwstress, because it's not a good test
 do
-  gnumake -r -f sus8gc.gmk $test ||
+  gnumake -r -f ${platform}.gmk $test ||
     die "Unable to build test $test of trunk"
   for variety in hi ci ti
   do
-    ./sus8gc/$variety/$test ||
+    ./$platform/$variety/$test ||
       die "Failed test $variety/$test of trunk"
     rm mpsio.log
   done
 done
+
+gnumake -r -f $platform.gmk clean ||
+  die "Unable to clean up trunk"
