Use the makefile target testrun
Copied from Perforce
 Change: 19821
 ServerID: perforce.ravenbrook.com

diff --git a/mps/home/bin/build/MM_src_trunk b/mps/home/bin/build/MM_src_trunk
--- a/mps/home/bin/build/MM_src_trunk
+++ b/mps/home/bin/build/MM_src_trunk
@@ -2,7 +2,7 @@
 #
 # Build and test MM (the MM_src compound) at tip of the trunk
 # 
-# $HopeName: HOMEmm!bin:build:MM_src_trunk(trunk.24) $
+# $HopeName: HOMEmm!bin:build:MM_src_trunk(trunk.25) $
 
 
 script="`basename $0`"
@@ -36,20 +36,17 @@ function build-lib {
   for variety in hi ci ti wi he ce
   do
     date
-    gnumake -r -f ${platform}.gmk VARIETY=$variety $1 ||
+    gnumake -rf ${platform}.gmk VARIETY=$variety $1 ||
       die "Unable to build library $1 of trunk"
   done
 }
 
 ## Build and run a test
-function do-test {
+function do-tests {
   for variety in hi ci ti wi he ce
   do
-    date
-    gnumake -r -f ${platform}.gmk VARIETY=$variety $1 ||
-      die "Unable to build test $variety/$1 of trunk"
-    ./$platform/$variety/$1 ||
-      die "Failed test $variety/$1 of trunk"
+    gnumake -rf ${platform}.gmk VARIETY=$variety $1 ||
+      die "$1 failed for variety $variety of trunk"
     rm mpsio.log
   done
 }
@@ -62,20 +59,16 @@ cd src
 
 build-lib mmsw.a
 
-do-test epvmss
+do-tests testrunep
 
 ### Then clean up and do the others.
 
-gnumake -r -f $platform.gmk clean ||
+gnumake -rf $platform.gmk clean ||
   die "Unable to clean up trunk"
 
 build-lib mps.a 
 
-for test in amcss lockcov locv mpmss mpsicv poolncv \
-            qs finalcv arenacv awlut amsss
-do
-  do-test $test
-done
+do-tests testrun
 
-gnumake -r -f $platform.gmk clean ||
+gnumake -rf $platform.gmk clean ||
   die "Unable to clean up trunk"
