Give control of varieties to caller
Copied from Perforce
 Change: 21097
 ServerID: perforce.ravenbrook.com

diff --git a/mps/home/bin/mmqa/MMQA_epcore_brisling b/mps/home/bin/mmqa/MMQA_epcore_brisling
--- a/mps/home/bin/mmqa/MMQA_epcore_brisling
+++ b/mps/home/bin/mmqa/MMQA_epcore_brisling
@@ -2,12 +2,13 @@
 #
 # Build the MMsrc compound at tip of branch MM_epcore_brisling, and run QA tests
 # 
-# $HopeName: HOMEmm!bin:mmqa:MMQA_epcore_brisling(trunk.2) $
+# $HopeName: HOMEmm!bin:mmqa:MMQA_epcore_brisling(trunk.3) $
 
 
 script="`basename $0`"
 platform=$1
-varieties="hi we"
+shift
+varieties=$*
 
 
 msg () {
@@ -53,13 +54,16 @@ mmqa_tests () {
   MMQA_LOG_DIR=./log  export MMQA_LOG_DIR
   for variety in $varieties
   do
-    MMQA_MPS_LINK_OBJ="$mmsrc/$platform/$variety/mmsw.a \
-                       $mmsrc/$platform/$variety/mpsplan.a" \
-                       export MMQA_MPS_LINK_OBJ
-    MMQA_MAIL_SUBJECT="MMQA $1 for variety $variety of MM_epcore_brisling:" \
-                       export MMQA_MAIL_SUBJECT
-    perl5 ./test/qa clib || die "Unable to compile MMQA library"
-    perl5 ./test/qa runset $1  || die "Failed to run MMQA testset"
+    if [ "$variety" != "$2" ]
+    then
+      MMQA_MPS_LINK_OBJ="$mmsrc/$platform/$variety/mmsw.a \
+                        $mmsrc/$platform/$variety/mpsplan.a" \
+                         export MMQA_MPS_LINK_OBJ
+      MMQA_MAIL_SUBJECT="MMQA $1 for variety $variety of MM_epcore_brisling:" \
+                         export MMQA_MAIL_SUBJECT
+      perl5 ./test/qa clib || die "Unable to compile MMQA library"
+      perl5 ./test/qa runset $1  || die "Failed to run MMQA testset"
+    fi
   done
 }
 
@@ -80,7 +84,8 @@ build_lib mpsplan.a
 
 
 cd $HOME/Builds/MMQA &&
-mmqa_tests testsets/dailysw
+mmqa_tests testsets/dailysw &&
+mmqa_tests testsets/dailyswa we
 
 
 # If the tests succeeded, delete the junk
diff --git a/mps/home/bin/mmqa/MMQA_src_trunk b/mps/home/bin/mmqa/MMQA_src_trunk
--- a/mps/home/bin/mmqa/MMQA_src_trunk
+++ b/mps/home/bin/mmqa/MMQA_src_trunk
@@ -2,12 +2,13 @@
 #
 # Build the MMsrc compound at tip of the trunk, and run QA tests
 # 
-# $HopeName: HOMEmm!bin:mmqa:MMQA_src_trunk(trunk.3) $
+# $HopeName: HOMEmm!bin:mmqa:MMQA_src_trunk(trunk.4) $
 
 
 script="`basename $0`"
 platform=$1
-varieties="hi we"
+shift
+varieties=$*
 
 
 msg () {
@@ -53,13 +54,16 @@ mmqa_tests () {
   MMQA_LOG_DIR=./log  export MMQA_LOG_DIR
   for variety in $varieties
   do
-    MMQA_MPS_LINK_OBJ="$mmsrc/$platform/$variety/$2 \
-                       $mmsrc/$platform/$variety/mpsplan.a" \
-                       export MMQA_MPS_LINK_OBJ
-    MMQA_MAIL_SUBJECT="MMQA $1 for variety $variety of trunk:" \
-                       export MMQA_MAIL_SUBJECT
-    perl5 ./test/qa clib || die "Unable to compile MMQA library"
-    perl5 ./test/qa runset $1  || die "Failed to run MMQA testset"
+    if [ "$variety" != "$3" ]
+    then
+      MMQA_MPS_LINK_OBJ="$mmsrc/$platform/$variety/$2 \
+                         $mmsrc/$platform/$variety/mpsplan.a" \
+                         export MMQA_MPS_LINK_OBJ
+      MMQA_MAIL_SUBJECT="MMQA $1 for variety $variety of trunk:" \
+                         export MMQA_MAIL_SUBJECT
+      perl5 ./test/qa clib || die "Unable to compile MMQA library"
+      perl5 ./test/qa runset $1  || die "Failed to run MMQA testset"
+    fi
   done
 }
 
@@ -82,7 +86,8 @@ build_lib mmsw.a
 build_lib mpsplan.a
 
 cd $HOME/Builds/MMQA &&
-mmqa_tests testsets/dailysw mmsw.a
+mmqa_tests testsets/dailysw mmsw.a &&
+mmqa_tests testsets/dailyswa mmsw.a we
 
 
 ### Then clean up and do the others.
